
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 2;
  public static final int HORARIO = 15;
  public static final int COMA = 5;
  public static final int USUARIO = 9;
  public static final int SALON = 11;
  public static final int EOF = 0;
  public static final int PAL = 3;
  public static final int CURSO = 12;
  public static final int PUNTCOMA = 8;
  public static final int EDIFICIO = 10;
  public static final int PARI = 6;
  public static final int ESTUDIANTE = 13;
  public static final int CATEDRATICO = 14;
  public static final int TIPO = 4;
  public static final int error = 1;
  public static final int ASIGNAR = 16;
  public static final int PARD = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "PAL",
  "TIPO",
  "COMA",
  "PARI",
  "PARD",
  "PUNTCOMA",
  "USUARIO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "ESTUDIANTE",
  "CATEDRATICO",
  "HORARIO",
  "ASIGNAR"
  };
}

